-- 코드를 입력하세요

SELECT FOOD_PRODUCT2.PRODUCT_ID, FOOD_PRODUCT2.PRODUCT_NAME, SUM(FOOD_ORDER2.AMOUNT * FOOD_PRODUCT2.PRICE) AS TOTAL_SALES FROM 
(SELECT * FROM FOOD_ORDER
WHERE PRODUCE_DATE >= '2022-05-01 00:00:00' AND PRODUCE_DATE < '2022-06-01 00:00:00') FOOD_ORDER2
INNER JOIN
(SELECT * FROM FOOD_PRODUCT) FOOD_PRODUCT2
ON FOOD_ORDER2.PRODUCT_ID = FOOD_PRODUCT2.PRODUCT_ID 
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC